from __future__ import annotations

import streamlit as st

from dashboard.components.metric_cards import render_metric_cards
from dashboard.utils.data_loader import (
    check_required_outputs,
    load_prediction_explanations,
    load_stream_metrics,
    load_shap_assets,
    parse_phase_distribution,
    parse_summary_metrics,
)
from dashboard.utils.helpers import system_health_status, summary_to_display
from dashboard.utils.model_loader import get_model_status


def render():
    st.title("Overview Test")
    st.success("Overview page works!")
    summary_metrics = parse_summary_metrics()
    summary_cards = summary_to_display(summary_metrics)
    phase_stats = parse_phase_distribution()
    status, status_color = system_health_status(
        summary_metrics.get("accuracy"), summary_metrics.get("drift_events")
    )

    render_metric_cards(
        {**summary_cards, "drift_events": summary_metrics.get("drift_events"), "retrain_count": summary_metrics.get("retrain_count"), "total_chunks": summary_metrics.get("total_chunks")},
        status,
        status_color,
        phase_stats.get("attack_samples"),
        phase_stats.get("benign_samples"),
        phase_stats.get("total_samples") or summary_metrics.get("stream_samples"),
    )

    st.markdown("---")
    st.subheader("IDS Output Health")
    st.write("This overview consumes the latest real outputs generated by the IDS pipeline. No models are retrained by the dashboard.")
    st.markdown(f"**Model artifact status:** {get_model_status()}")

    explanation_json = load_prediction_explanations()
    if explanation_json is not None:
        st.markdown(
            f"**Explained stream samples:** {explanation_json['metadata'].get('explained_samples', 'N/A')} / {explanation_json['metadata'].get('stream_samples', 'N/A')}"
        )

    shap_assets = load_shap_assets()
    asset_list = [path for path in shap_assets.values() if path is not None]
    st.markdown(f"**Loaded explainability files:** {len(asset_list)}")
